config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  get 'pages/ui', to: 'pages#ui'
  get 'pages/dash', to: 'pages#dash', as: 'dash'
  get 'pages/info', to: 'pages#info', as: 'info'
  resources :presets do
    resources :activities
    resources :timer_sessions, only: [:create]
  end
  resources :breaks, only: [:index, :show, :update]
  resources :timer_sessions, only: [:index, :show, :destroy] do
    resources :breaks, only: [:new, :create, :show]
  end
  get 'timer_sessions/:id/stats', to: 'timer_sessions#stats', as: 'stats'
  resources :start_timer_sessions, only: [:update]
  resources :end_timer_sessions, only: [:update]
  resources :break_timer, only: [:update]
  resources :activities, only: [:destroy]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/timer_session.rb
class TimerSession < ApplicationRecord
  belongs_to :preset
  has_many :breaks,  dependent: :destroy
  # has_many :timer_sessions
end

app/controllers/timer_sessions_controller.rb
require 'date'

class TimerSessionsController < ApplicationController
  def index

    @navbar_render = true
    @timer_sessions = current_user.timer_sessions
    @stats = current_user.overall_stats
    @daily = current_user.today_activity_stats
    @total_focus = @total_break = @daily_focus = @daily_break = 0

    @timer_sessions.each do |timer_session|
      @total_focus += timer_session.preset.focus_timer * timer_session.breaks.length
      @total_break += timer_session.preset.break_duration * timer_session.breaks.length
      if timer_session.created_at.between?(Time.zone.today.beginning_of_day, Time.zone.today.end_of_day)
        @daily_focus += timer_session.preset.focus_timer * timer_session.breaks.length
        @daily_break += timer_session.preset.break_duration * timer_session.breaks.length
      end
    end
  @stats.unshift(["Focusing", @total_focus])
  @daily["Focusing"] = @daily_focus
  @daily = @daily.to_a.sort_by { |stat| -stat.last}.to_h

  end

  def show
    @navbar_render = true
    @timer_session = TimerSession.find(params[:id])
  end

  def new
    @navbar_render = true
    @timer_session = TimerSession.new
  end

  def create
    @navbar_render = true
    @timer_session = TimerSession.new
    @timer_session.preset = Preset.find(params[:preset_id])
    if @timer_session.save
      redirect_to timer_session_path(@timer_session)
    else
      render :new
    end
  end

  def destroy
  end

  def stats
    @navbar_render = true
    @timer_session = TimerSession.find(params[:id])
    if @timer_session.breaks.first == nil
      redirect_to timer_session_path(@timer_session)
    end
    @stats = {
      # "Workday" => @timer_session.preset.working_day * 60,
      "Focusing" => @timer_session.preset.focus_timer.to_i * @timer_session.breaks.count.to_i
    }
    @timer_session.breaks.each do |b|
      if @stats[b.activity.name].present?
        @stats[b.activity.name] += @timer_session.preset.break_duration
      else
        @stats[b.activity.name] = @timer_session.preset.break_duration
      end
    end
    @working_time = @timer_session.preset.working_day
    if @timer_session.breaks.first != nil
      @breaks_time = @timer_session.breaks.count.to_i * @timer_session.breaks.first.length.to_i
    else
      @breaks_time = 0
    end
    @focus_time = @timer_session.preset.focus_timer.to_i * @timer_session.breaks.count.to_i
    @remaining_time = @working_time * 60 - @focus_time - @breaks_time
  end


  private

  def timer_session_params
    params.require(:timer_session).permit(:ends_at, :starts_at)
  end
end

app/views/timer_sessions/create.html.erb
<h1>TimerSessions#create</h1>
<p>Find me in app/views/timer_sessions/create.html.erb</p>

app/views/timer_sessions/destroy.html.erb
<h1>TimerSessions#destroy</h1>
<p>Find me in app/views/timer_sessions/destroy.html.erb</p>

app/views/timer_sessions/edit.html.erb
<h1>TimerSessions#edit</h1>
<p>Find me in app/views/timer_sessions/edit.html.erb</p>

app/views/timer_sessions/index.html.erb
<%= javascript_include_tag "https://www.gstatic.com/charts/loader.js", "chartkick" %>
<div class="lifetime-container">
  <div class="lifetime-title">
    <h1>Daily Stats</h1>
  </div>
  <div class="daily-stats">
    <% if @daily_focus != nil && @daily_break != nil %>
      <div class="total-spent">
        <%= "Total minutes spent = " %>
        <%= @daily_focus + @daily_break %>
      </div>
      <%end %>
      <div class="stats-graph">
      <%= pie_chart(@daily, ytitle: "Time (minutes)", xtitle: "Activity", colors: [ "#00008B", "#4B0082", "#8B0000", "#008000"])  %>
      <% if @daily_focus != nil && @daily_break != nil %>
        <% @daily.each do |key, value| %>
          <%= "#{key}: #{value} minutes" %>
          <br>
        <% end %>
      <% else %>
        <%= "No stats for today" %>
      <% end %>
    </div>
  </div>
  <div class="lifetime-title">
    <h1>Lifetime Stats</h1>
  </div>
  <div class="lifetime-stats">
    <div class="total-spent">
      <%= "Total minutes spent = " %>
      <%= @total_focus + @total_break %>
    </div>
    <div class="container-chart">
    <div class="stats-graph">
    <%= pie_chart(@stats, ytitle: "Time (minutes)", xtitle: "Activity", colors: [ "#00008B", "#4B0082", "#8B0000", "#008000"])  %>
    <% @stats.each do |key, value| %>
      <%= "#{key}: #{value} minutes" %>
      <br>
    <% end %>
    </div>
  </div>
    <br>
  </div>

    <div class="lifetime-exit">
      <% if @timer_sessions.last != nil %>
        <%= link_to "Stats for last timer session", stats_path(@timer_sessions.last) %>
      <% end %>
    </div>
    <div class="action-buttons-box">
      <%= link_to "Exit", presets_path, :class=> "btn obbtn rexit" %>
    </div>
    </div>

  </div>
</div>
<div class="bottom-blank">
</div>

app/views/timer_sessions/new.html.erb
<h1>TimerSessions#new</h1>
<p>Find me in app/views/timer_sessions/new.html.erb</p>

app/views/timer_sessions/show.html.erb
<!--  START OF NEW CODE - TIMER SHOW -->
<div class="container text-center">
    <div class="row">
      <div class="col-xs-12 col-md-6 col-md-offset-3">
        <div class="title-box">
        <h1 class="h1title"><%= @timer_session.preset.name %></h1>
        </div>
      </div>
    </div>
  <div class="row">
    <div class="col-xs-12 col-md-6 col-md-offset-3">
      <div class="sub-title-box">
         <p class="pbold">Stay focused</p>
      </div>
    </div>
  </div>

  <div class="col-xs-8 col-xs-offset-2 col-md-4 col-md-offset-4">
    <div class="middle-content">
      <div id="timer2" class="timerfont" data-limit="<%= @timer_session.preset.focus_timer %>" data-sessionid="<%= @timer_session.id %>" data-day="<%= @timer_session.preset.focus_timer %>">
            <%= @timer_session.preset.duration(:focus_timer) %>
      </div>

    </div>
  </div>
    <div class="col-xs-12 col-md-6 col-md-offset-3">
      <div class="action-buttons-box">
        <%= link_to start_timer_session_path(@timer_session), method: :patch, remote: true do %>
        <i class="far fa-play-circle fa-3x whiteicon"></i>
        <% end %>

          <%= link_to new_timer_session_break_path(@timer_session) do  %>
          <i class="far fa-stop-circle fa-3x whiteicon"></i>
        <% end %>
        </div>
        <div class="action-buttons-box">
        <%= link_to "Exit", presets_path, :class=> "btn obbtn rexit" %>
         </div>
        <div class="action-buttons-box">
        <%= link_to "Session stats", stats_path(@timer_session), :class=> "btn obbtn rexit plight" %>
         </div>
          </div>
        </div>
      </div>
    </div>
    <div class="bottom-blank">
    </div>
  </div>
</div>

<%= javascript_pack_tag 'easytimer' %>

app/views/timer_sessions/stats.html.erb
<%= javascript_include_tag "https://www.gstatic.com/charts/loader.js", "chartkick" %>


<div class="stats-container">
  <div class="stats-title">
    <h2>Session Progress</h2>
  </div>
  <div class="time-stats">
    <div class="time">
      <%= "Time allocated for today = " %>
      <%= @working_time * 60 %>
      <%= "minutes" %>
      <br>
      <%= "Time remaning = " %>
      <% if @remaining_time >= 0 %>
        <%= @remaining_time %>
      <% else %>
        <%= "0" %>
      <% end %>
      <%= "minutes" %>
    </div>
  </div>
  <div class="stats-graph">
    <%= column_chart(@stats, ytitle: "Time (minutes)", xtitle: "Activity", colors: ["#00008B", "#b00"])  %>
    <div class="time-spent">
      <% @stats.each do |key, value| %>
        <%= "#{value} minutes #{key}" %>
        <br>
      <% end %>
    </div>
  </div>
  <div class="graph-buttons">
    <div class="action-buttons-box">
      <%= link_to "Continue", timer_session_path(@timer_session), :class=> "btn obbtn rexit" %>
    </div>
    <div class="action-buttons-box">
      <%= link_to "Exit to home", presets_path, :class=> "btn obbtn rexit" %>
    </div>
  </div>
  <div class="bottom-blank">
  </div>
</div>