config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  get 'pages/ui', to: 'pages#ui'
  get 'pages/dash', to: 'pages#dash', as: 'dash'
  get 'pages/info', to: 'pages#info', as: 'info'
  resources :presets do
    resources :activities
    resources :timer_sessions, only: [:create]
  end
  resources :breaks, only: [:index, :show, :update]
  resources :timer_sessions, only: [:index, :show, :destroy] do
    resources :breaks, only: [:new, :create, :show]
  end
  get 'timer_sessions/:id/stats', to: 'timer_sessions#stats', as: 'stats'
  resources :start_timer_sessions, only: [:update]
  resources :end_timer_sessions, only: [:update]
  resources :break_timer, only: [:update]
  resources :activities, only: [:destroy]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/_slider.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">

  <!-- Indicators -->
<!--   <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol> -->

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag "blank_transparent.png" %>
      <div class="carousel-caption">
        <h2 class="h2bold">
        Do more, feel good</h2>
        <p class="">
        Focus more by defining periodical focus/break times
        with the tried and tested pomodoro technique.
        Customize these to what works best for you.</p>
      </div>
    </div>

    <div class="item">
     <%= image_tag "blank_transparent.png", class: "img-carousel" %>
      <div class="carousel-caption">
        <h2 class="h2bold">Work hard, rest hard</h2>
        <p class="">
          Combine intense focus
            of the pomodoro technique with enhanced
            breaks through meditation and deep breathing.
          </p>
      </div>
    </div>

    <div class="item">
      <%= image_tag "blank_transparent.png" %>

      <div class="carousel-caption">
        <h2 class="h2bold">Less distractions</h2>
        <p class="">
          Plan your social media use and limit it to those break times. Our daily stats will
        help you see where you are.</p>
      </div>
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel"
  role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
   <script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


<!-- Second Slider -->

app/views/pages/_sliderdash.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel" >

  <!-- Indicators -->
<!--   <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol> -->

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag "blank_transparent.png" %>
      <div class="carousel-caption">
        <h2 class="h2bold">
        More focus</h2>
        <p class="plight">
        Pomodoro is a timeboxing technique with 25 minutes
        focus time and 5 minutes breaks. It has helped countless
        people to get more done.
       </p>
      </div>
    </div>
    <div class="item">
     <%= image_tag "blank_transparent.png", class: "img-carousel" %>
      <div class="carousel-caption">
        <h2>Work & rest hard</h2>
        <p class="plight">
          Work hard, and plan your breaks. Our spotify integration
          will provide you with fitting relaxing music or meditation.
          </p>
      </div>
    </div>

    <div class="item">
      <%= image_tag "blank_transparent.png" %>

      <div class="carousel-caption">
        <h2 class="h2bold">Less distractions</h2>
        <p class="plight text-justify">
        Stay closer to your enemies, give yourself time to check your
        social media. Our stats will keep you honest.</p>
      </div>
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel"
  role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
   <script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


<!-- Second Slider -->

app/views/pages/dash.html.erb
<% content_for :meta_title, "#{@user.email} Dashboard" %>
<% content_for :meta_description, "#{@user.email} Dashboard" %>
<% title "Dashboard" %>

  <div class="container text-center">
    <div class="row">
      <div class="col-xs-12 col-md-6 col-md-offset-3">
        <div class="title-box">
          <h1 class="h1title">
          </h1>
          <% avatar_url = current_user.facebook_picture_url || "http://placehold.it/30x30" %>
          <%= image_tag avatar_url, class: "obavatar-large", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <h2 class="h2subtitle">
            Welcome <%= @user.first_name %>
            </h2>
          <p class="pquote"><script type="text/javascript" src="https://www.brainyquote.com/link/quotebr.js"></script></p>
          <br>
        </div>
      </div>
    </div>


  <div class="col-xs-12 col-md-6 col-md-offset-3">

   <div class="middle-content-dash">
    <div class="dashbox psmaller">
    <strong>This week vs. Last week</strong>
    <br>
    Meditation: +50% <br>
    Focus time: +20% <br>
    <br>

    Have a good session.<br>

    </div>
  </div>
</div>


    <div class="col-xs-12 col-md-6 col-md-offset-3">
      <div class="action-buttons-box">
        <%= link_to "Start Session", presets_path, :class=> "btn obbtn resume start-session" %>
      </div>
    </div>

    <div class="col-xs-12 col-md-6 col-md-offset-3 ">
      <div class="action-buttons-box">
        <%= link_to "How to", info_path, :class=> "btn obbtn rexit" %>
      </div>
    </div>
  </div>
</div>
<div class="bottom-blank">
</div>

app/views/pages/home.html.erb
<div class="container-fluid text-center homey">
    <div class="row">
      <div class="col-xs-12 col-md-6 col-md-offset-3">
        <div class="title-box">
          <h1 class="title-home-page"><%= image_tag("blue_logo.png", :size => "65x65") %> ne Breath Timer</h1>
          <!-- <h2>Plan your time, get your balance</h2> -->
        </div>
      </div>
    </div>


  <div class="col-xs-12 col-md-6 col-md-offset-3">
    <div class="obcarousel">
      <%= render "slider" %>
    </div>
  </div>


    <div class="col-xs-12 col-md-6 col-md-offset-3">
      <div class="action-buttons-box">
        <%= link_to "I'm new", new_user_registration_path, :class=> "btn obbtn resume  home-cta" %>
      </div>
    </div>

    <div class="col-xs-12 col-md-6 col-md-offset-3 ">
      <div class="action-buttons-box">
        <%= link_to "Sign in", user_session_path, :class=> "btn obbtn rexit" %>
      </div>
    </div>
  </div>
</div>

app/views/pages/info.html.erb
<% content_for :meta_title, "How To" %>
<% content_for :meta_description, "How To" %>
<% title "How to" %>
<div class="container text-center">
  <div class="row">
    <div class="col-xs-12 col-md-6 col-md-offset-3">

        <h2 class="h2subtitle">
        How to use <br>
        One Breath Timer
        </h2>

    </div>
  </div>
  <div class="col-xs-10 col-xs-offset-1 col-md-6 col-md-offset-3">
    <div class="middle-content">
        <br>
        <p class="text-left">
          <i class="fas fa-home whiteicon text-center"> About Us</i><br>
          One Breath was named after the saying that one mindful breath is all it takes to change your day to the better, we wholeheartedly believe that, that's why
          we focus on the breaks as much as the work.
        <br><br>
          <i class="fas fa-clock whiteicon"> Timing</i><br>
          Our timer uses timeboxing technique made famous by the pomodoro timer and Cal Newport's Deep Work. The basic logic is to
          set time to focus times time to take breaks or get distracted. This way one can focus on one thing at a time and get the most done.
          <br><br>
          <i class="fas fa-chart-line whiteicon"> Stats</i><br>
          Our Stats will let you know how well you are doing, through daily stats you will know
          how much closer you are getting to your goals and keep pushing.


      </p>
    </div>
  </div>
  <div class="col-xs-12 col-md-6 col-md-offset-3">
    <div class="action-buttons-box">
      <%= link_to "Get started", presets_path, :class=> "btn obbtn resume" %>
    </div>
  </div>
</div>
</div>
</div>

app/views/pages/ui.html.erb
<head>

</head>
<div class="container text-center">
  <div class="wrapper">
    <div class="row">
      <div class="col-xs-12 col-md-6 col-md-offset-3">
        <div class="title-box">
        <h1>One Breath</h1>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-md-6 col-md-offset-3">
        <div class="sub-title-box">
          <h2>The UI Collection</h2>
        </div>
      </div>
    </div>

  <div class="col-xs-12 col-md-6 col-md-offset-3">
    <div class="obcarousel">
      <h2> The slider</h2>
      <%= render "slider" %>
    </div>
  </div>




    <div class="col-xs-8 col-xs-offset-2 col-md-4 col-md-offset-4">
      <div class="middle-content">
        <h1>H1 Tag</h1>
        <h2>H2 Tag</h2>
        <p class="text-justify">
        Body Text
        Meditation is a age old technique from the sages of the Himalayas. These days people are stressed, I’m sure you are too, and you are looking for a way out. Using one breath is going to solve all your problems, even help you stop smoking crack on the weekends.
        </p>
      </div>
    </div>

    <div class="col-xs-12 col-md-6 col-md-offset-3">
      <div class="action-buttons-box">
        resume Class Button <br>
        <%= link_to "I'm new", "#", :class=> "btn obbtn resume" %>
         <div class="action-buttons-box">
        rexit Class Button <br>
        <%= link_to "Sign In", "#", :class=> "btn obbtn rexit" %>
        </div>
         <div class="action-buttons-box">
        sign-in Class Button <br>
        <%= link_to "Sign In", "#", :class=> "btn obbtn sign-in" %>
        </div>
         <div class="action-buttons-box">
        sign-in-fb Class Button <br>
        <%= link_to "Sign In Fb", "#", :class=> "btn obbtn sign-in-fb" %>
        </div>
         <div class="action-buttons-box">
        flow-selected Class Button <br>
        <%= link_to "selected", "#", :class=> "btn obbtn flow-selected" %>
        </div>
        <div class="action-buttons-box">
        flow-unselected Class Button <br>
        <%= link_to "unselected", "#", :class=> "btn obbtn flow-unselected" %>
        <br>
        <%= link_to "link a class", presets_path %>
        </div>
  </div>
 </div>
  </div>
</div>