config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  get 'pages/ui', to: 'pages#ui'
  get 'pages/dash', to: 'pages#dash', as: 'dash'
  get 'pages/info', to: 'pages#info', as: 'info'
  resources :presets do
    resources :activities
    resources :timer_sessions, only: [:create]
  end
  resources :breaks, only: [:index, :show, :update]
  resources :timer_sessions, only: [:index, :show, :destroy] do
    resources :breaks, only: [:new, :create, :show]
  end
  get 'timer_sessions/:id/stats', to: 'timer_sessions#stats', as: 'stats'
  resources :start_timer_sessions, only: [:update]
  resources :end_timer_sessions, only: [:update]
  resources :break_timer, only: [:update]
  resources :activities, only: [:destroy]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/preset.rb
class Preset < ApplicationRecord
  belongs_to :user, optional: true
  has_many :timer_sessions, dependent: :destroy
  has_many :activities,  dependent: :destroy
  has_many :breaks, through: :timer_sessions
  #validates :activity, presence: true
  validates :working_day, presence: true
  validates :focus_timer, presence: true
  validates :break_duration, presence: true
  validates :name, presence: true

  after_create :populate_default_activities

  def string_duration
    total_seconds = focus_timer * 60
    seconds = total_seconds % 60
    minutes = (total_seconds / 60) % 60
    hours = total_seconds / (60 * 60)

    format("%02d:%02d:%02d", hours, seconds, minutes) #=> "01:00:00"

  end

  private

  def populate_default_activities
    ["Meditation", "Social Media", "Reading"].each do |act|
      Activity.create(name: act, chosen: true, preset: self)
   end
  end
 end

app/controllers/presets_controller.rb
class PresetsController < ApplicationController
  before_action :set_preset, only: [:show, :edit, :udpate]
  before_action :set_user, only: [:new, :edit ]

  def index
    @pomodoro = Preset.find_by(name: "Pomodoro")
    @presets = Preset.where(user_id: current_user.id)
    @navbar_render = true
  end

  def show
  end

  def new
    @preset = Preset.new
    @navbar_render = true
  end

  def create
    @preset = Preset.new(preset_params)
    @preset.user = current_user
    if @preset.save
      if params[:commit] == "Start Timer"
        timer = TimerSession.create(preset_id: @preset.id)
        timer_session_path(timer)
      else
        redirect_to new_preset_activity_path(@preset)
      end
    else
    render :new
  end
  end

  def edit
    @navbar_render = true
  end

  def update
    @preset = Preset.find(params[:id])
    if params[:commit] == "Start Timer"
      @preset.update(preset_params)
      timer = TimerSession.create(preset_id: @preset.id)
      redirect_to timer_session_path(timer)
    elsif params[:commit] == "done editing breaks"
        params[:preset].each do |activity, value_checked|
        if value_checked == "0"
          act = @preset.activities.find_by(name: activity)
          act.destroy if act
        else
          @preset.activities.find_by(name: activity)
        end
      end
      timer = TimerSession.create(preset_id: @preset.id)
      redirect_to timer_session_path(timer)
    else
      @preset.update(preset_params)
      redirect_to  preset_activities_path(@preset)
    end
  end

  def destroy
    @preset = Preset.find(params[:id])
    @preset.destroy
    redirect_to presets_path
  end

   private

  def preset_params
    params.require(:preset).permit(:name, :working_day, :focus_timer, :break_duration)
  end

  def set_preset
    @preset = Preset.find(params[:id])
  end

  def set_user
    @user = current_user
  end
end

app/views/presets/_form.html.erb
 <div class="col-xs-10 col-xs-offset-1 col-md-4 col-md-offset-4">
	<div class="middle-content">
  	<%= simple_form_for [@preset], defaults: { input_html: { class: 'form-control' } } do |f| %>
    <div id=name><%= f.input :name, label:"Name your Flow",placeholder: 'Deep Work'%></div>
		<div id=working_day><%= f.input :working_day, label: "Total hours" %></div>
		<div id=focus_timer><%= f.input :focus_timer, label: "Minutes per session" %></div>
		<div id=break_duration><%= f.input :break_duration, label: "Minutes per break" %></div>
  </div>
<!--
      <div class="action-buttons-box">
        <%= f.submit "Start Timer", :class=> "btn obbtn sign-in" %>
      </div> -->
      <div class="action-buttons-box">
        <%= f.submit "Create flow", :class=> "btn obbtn resume" %>
      </div>
    </div>
    <% end %>
  </div>

app/views/presets/destroy.js.erb
document.querySelector("[id='<%= @preset.id %>']")
  .remove();

app/views/presets/edit.html.erb
<div class="container text-center">

    <div class="row">
      <div class="col-xs-12 col-md-6 col-md-offset-3">
        <div class="title-box">
        <h1>Edit your preset</h1>
        </div>
      </div>
    </div>
  <%= render 'form' %>
</div>
<div class="bottom-blank">
</div>

<%= javascript_pack_tag 'slider' %>
<%= stylesheet_pack_tag 'slider-style' %>

app/views/presets/index.html.erb
<div class="container text-center">
  <div class="row">
    <div class="col-xs-12 col-md-6 col-md-offset-3">
      <div class="title-box">
        <h1 class="h1title">Pick your flow</h1>
      </div>
    </div>
  </div>
    <div class="col-xs-10 col-xs-offset-1 col-md-6 col-md-offset-3">
      <div class="sub-title-box">
        <p class="pbold">

          Create your new timer preset flow or select one.

        </p>
      </div>
    </div>
  <div class="col-xs-10 col-xs-offset-1 col-md-4 col-md-offset-4">
    <div class="middle-content">
      <div class="presets-box presets-box-button">
          <div class="flex preset-box-content">
            <%= link_to preset_timer_sessions_path(@pomodoro), method: :post, class: "preset-link" do %>
              <p class="pbold"><%= @pomodoro.name %></p>
            <% end %>
            <div>
             <%= image_tag "tomato.svg", class: "white-svg"%>
            </div>
          </div>
      </div>
      <% @presets.each do |preset| %>
      <div class="presets-box presets-box-button">
          <div class="flex preset-box-content">
            <%= link_to preset_timer_sessions_path(preset), method: :post, class: "preset-link" do %>
              <p class="pbold2"><%= preset.name %></p>
            <% end %>
            <div class="button-presets-action">
              <%= link_to edit_preset_path(preset) do %>
                <i class="far fa-edit whiteicon"></i>
              <% end %>
              <%= link_to preset , method: :delete do %>
                <i class="fa fa-trash whiteicon" aria-hidden="true"></i>
              <% end %>
            </div>
          </div>
      </div>
      <% end %>
      <div class="presets-box presets-box-button">
        <div class="flex preset-box-content">
          <%= link_to new_preset_path, :class=> "" do %>
            <p class="pbold2">Create new flow</p>
          <% end %>
          <div>
      </div>
    </div>
  </div>
</div>
<div class="bottom-blank">
</div>

app/views/presets/new.html.erb
<div class="container text-center">
 <div class="row">
      <div class="col-xs-12 col-md-6 col-md-offset-3" >
        <div class="title-box">
        <h1 class="h1title">Make it flow</h1>
        </div>
      </div>
    </div>

  <div class="row">
    <div class="col-xs-10 col-xs-offset-1 col-md-6 col-md-offset-3">
      <div class="sub-title-box">
        <p class="pbold">How do you want this work session to look?</p>
      </div>
    </div>
  </div>
    <%= render 'form' %>
</div>
<div class="bottom-blank">
</div>
<%= javascript_pack_tag 'slider' %>
<%= stylesheet_pack_tag 'slider-style' %>

app/views/presets/show.html.erb
<h1>Presets#show</h1>
<p>Find me in app/views/presets/show.html.erb</p>